config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_parts
  resources :vehicles
  resources :prices
  resources :vehicle_models
  resources :suppliers
  resources :vehicle_brands

  resources :parts do
    collection { post :import }
  end

  root to: 'vehicles#index'
end

app/models/vehicle_model.rb
class VehicleModel < ApplicationRecord
  belongs_to :vehicle_brand, optional: :true
  has_many :parts
  has_many :vehicles
end

app/controllers/vehicle_models_controller.rb
class VehicleModelsController < ApplicationController
  before_action :set_vehicle_model, only: [:show, :edit, :update, :destroy]

  # GET /vehicle_models
  # GET /vehicle_models.json
  def index
    @vehicle_models = VehicleModel.order(vehicle_brand_id: :asc, name: :asc).page(params[:page])
  end

  # GET /vehicle_models/1
  # GET /vehicle_models/1.json
  def show
  end

  # GET /vehicle_models/new
  def new
    @vehicle_model = VehicleModel.new
  end

  # GET /vehicle_models/1/edit
  def edit
  end

  # POST /vehicle_models
  # POST /vehicle_models.json
  def create
    @vehicle_model = VehicleModel.new(vehicle_model_params)

    respond_to do |format|
      if @vehicle_model.save
        format.html { redirect_to @vehicle_model, notice: 'Vehicle model was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle_model }
      else
        format.html { render :new }
        format.json { render json: @vehicle_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_models/1
  # PATCH/PUT /vehicle_models/1.json
  def update
    respond_to do |format|
      if @vehicle_model.update(vehicle_model_params)
        format.html { redirect_to @vehicle_model, notice: 'Vehicle model was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle_model }
      else
        format.html { render :edit }
        format.json { render json: @vehicle_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_models/1
  # DELETE /vehicle_models/1.json
  def destroy
    @vehicle_model.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_models_url, notice: 'Vehicle model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_model
      @vehicle_model = VehicleModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_model_params
      params.require(:vehicle_model).permit(:name, :vehicle_brand_id, :fuel, :transmission)
    end
end

app/helpers/vehicle_models_helper.rb
module VehicleModelsHelper
end

app/views/vehicle_models/_form.html.erb
<%= form_with(model: vehicle_model, local: true) do |form| %>
  <% if vehicle_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle_model.errors.count, "error") %> prohibited this vehicle_model from being saved:</h2>

      <ul>
      <% vehicle_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :vehicle_brand_id %>
    <%= form.number_field :vehicle_brand_id %>
  </div>

  <div class="field">
    <%= form.label :fuel %>
    <%= form.text_field :fuel %>
  </div>

  <div class="field">
    <%= form.label :transmission %>
    <%= form.text_field :transmission %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicle_models/edit.html.erb
<h1>Editing Vehicle Model</h1>

<%= render 'form', vehicle_model: @vehicle_model %>

<%= link_to 'Show', @vehicle_model %> |
<%= link_to 'Back', vehicle_models_path %>

app/views/vehicle_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicle Models</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Vehicle brand</th>
      <th>Fuel</th>
      <th>Transmission</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicle_models.each do |vehicle_model| %>
      <tr>
        <td><%= vehicle_model.name %></td>
        <td><%= vehicle_model.vehicle_brand.name %></td>
        <td><%= vehicle_model.fuel %></td>
        <td><%= vehicle_model.transmission %></td>
        <td><%= link_to 'Show', vehicle_model %></td>
        <td><%= link_to 'Edit', edit_vehicle_model_path(vehicle_model) %></td>
        <td><%= link_to 'Destroy', vehicle_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle Model', new_vehicle_model_path %>

<%= paginate @vehicle_models %>

app/views/vehicle_models/new.html.erb
<h1>New Vehicle Model</h1>

<%= render 'form', vehicle_model: @vehicle_model %>

<%= link_to 'Back', vehicle_models_path %>

app/views/vehicle_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vehicle_model.name %>
</p>

<p>
  <strong>Vehicle brand:</strong>
  <%= @vehicle_model.vehicle_brand_id %>
</p>

<p>
  <strong>Fuel:</strong>
  <%= @vehicle_model.fuel %>
</p>

<p>
  <strong>Transmission:</strong>
  <%= @vehicle_model.transmission %>
</p>

<%= link_to 'Edit', edit_vehicle_model_path(@vehicle_model) %> |
<%= link_to 'Back', vehicle_models_path %>