config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_parts
  resources :vehicles
  resources :prices
  resources :vehicle_models
  resources :suppliers
  resources :vehicle_brands

  resources :parts do
    collection { post :import }
  end

  root to: 'vehicles#index'
end

app/models/vehicle_brand.rb
class VehicleBrand < ApplicationRecord
  has_many :vehicles
  has_many :vehicle_model
end

app/controllers/vehicle_brands_controller.rb
class VehicleBrandsController < ApplicationController
  before_action :set_vehicle_brand, only: [:show, :edit, :update, :destroy]

  # GET /vehicle_brands
  # GET /vehicle_brands.json
  def index
    @vehicle_brands = VehicleBrand.order(:name).page(params[:page])
  end

  # GET /vehicle_brands/1
  # GET /vehicle_brands/1.json
  def show
  end

  # GET /vehicle_brands/new
  def new
    @vehicle_brand = VehicleBrand.new
  end

  # GET /vehicle_brands/1/edit
  def edit
  end

  # POST /vehicle_brands
  # POST /vehicle_brands.json
  def create
    @vehicle_brand = VehicleBrand.new(vehicle_brand_params)

    respond_to do |format|
      if @vehicle_brand.save
        format.html { redirect_to @vehicle_brand, notice: 'Vehicle brand was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle_brand }
      else
        format.html { render :new }
        format.json { render json: @vehicle_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_brands/1
  # PATCH/PUT /vehicle_brands/1.json
  def update
    respond_to do |format|
      if @vehicle_brand.update(vehicle_brand_params)
        format.html { redirect_to @vehicle_brand, notice: 'Vehicle brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle_brand }
      else
        format.html { render :edit }
        format.json { render json: @vehicle_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_brands/1
  # DELETE /vehicle_brands/1.json
  def destroy
    @vehicle_brand.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_brands_url, notice: 'Vehicle brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_brand
      @vehicle_brand = VehicleBrand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_brand_params
      params.require(:vehicle_brand).permit(:name)
    end
end

app/helpers/vehicle_brands_helper.rb
module VehicleBrandsHelper
end

app/views/vehicle_brands/_form.html.erb
<%= form_with(model: vehicle_brand, local: true) do |form| %>
  <% if vehicle_brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle_brand.errors.count, "error") %> prohibited this vehicle_brand from being saved:</h2>

      <ul>
      <% vehicle_brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicle_brands/edit.html.erb
<h1>Editing Vehicle Brand</h1>

<%= render 'form', vehicle_brand: @vehicle_brand %>

<%= link_to 'Show', @vehicle_brand %> |
<%= link_to 'Back', vehicle_brands_path %>

app/views/vehicle_brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicle Brands</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicle_brands.each do |vehicle_brand| %>
      <tr>
        <td><%= vehicle_brand.name %></td>
        <td><%= link_to 'Show', vehicle_brand %></td>
        <td><%= link_to 'Edit', edit_vehicle_brand_path(vehicle_brand) %></td>
        <td><%= link_to 'Destroy', vehicle_brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle Brand', new_vehicle_brand_path %>

<%= paginate @vehicle_brands %>

app/views/vehicle_brands/new.html.erb
<h1>New Vehicle Brand</h1>

<%= render 'form', vehicle_brand: @vehicle_brand %>

<%= link_to 'Back', vehicle_brands_path %>

app/views/vehicle_brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vehicle_brand.name %>
</p>

<%= link_to 'Edit', edit_vehicle_brand_path(@vehicle_brand) %> |
<%= link_to 'Back', vehicle_brands_path %>