config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_parts
  resources :vehicles
  resources :prices
  resources :vehicle_models
  resources :suppliers
  resources :vehicle_brands

  resources :parts do
    collection { post :import }
  end

  root to: 'vehicles#index'
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :vehicle_part, optional: :true
  belongs_to :supplier, optional: :true
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.order(:vehicle_part_id).page(params[:page])
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:vehicle_part_id, :supplier_id, :price)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_with(model: price, local: true) do |form| %>
  <% if price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :part_id %>
    <%= form.number_field :part_id %>
  </div>

  <div class="field">
    <%= form.label :supplier_id %>
    <%= form.number_field :supplier_id %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prices</h1>

<table class="table">
  <thead>
    <tr>
      <th>Vehicle</th>
      <th>Part</th>
      <th>Supplier</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.vehicle_part.vehicle_name %></td>
        <td><%= price.vehicle_part.part.name %></td>
        <td><%= price.supplier&.name %></td>
        <td><%= price.price %></td>
        <td><%= link_to 'Show', price %></td>
        <td><%= link_to 'Edit', edit_price_path(price) %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_price_path %>

<%= paginate @prices %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part:</strong>
  <%= @price.vehicle_part_id %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @price.supplier_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @price.price %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>