config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_parts
  resources :vehicles
  resources :prices
  resources :vehicle_models
  resources :suppliers
  resources :vehicle_brands

  resources :parts do
    collection { post :import }
  end

  root to: 'vehicles#index'
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :vehicle_brand, optional: :true
  belongs_to :vehicle_model, optional: :true
  has_many :vehicle_parts
  has_many :parts, through: :vehicle_parts

  def name
    "#{self.year_model} #{self.vehicle_brand.name} #{self.vehicle_model.name}"
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    # @vehicles = Vehicle.order(vehicle_brand_id: :asc, year_model: :desc).page(params[:page])

    @q = Vehicle.ransack(params[:q])
    @vehicles = @q.result.includes(:vehicle_brand, :vehicle_model).page(params[:page])
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:year_model, :vehicle_brand_id, :vehicle_model_id, :chassis_number)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= simple_form_for(@vehicle) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <%#= f.input :vehicle_brand_id, as: :select, collection: VehicleBrand.order(:name), wrapper_html: { class: '' }, input_html: {class: "brand"} %>
    <%= f.input :vehicle_brand_id, as: :select, collection: VehicleBrand.order(:name), wrapper_html: { class: '' }, input_html: {class: "brand"} %>
    <%= f.grouped_collection_select :vehicle_model_id, VehicleBrand.order(:name), :vehicle_model, :name, :id, :name, { include_blank: true}, class: 'form-control' %>

    <%#= f.association :vehicle_brand, label: "Brand" %>
    <%#= f.association :vehicle_model, label: "Model" %>
    <%= f.input :chassis_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vehicles/_ransack.html.erb
<div class="py-4">
  <%= search_form_for @q do |f| %>

    <div class="form-row">
      <div class="col-auto">
        <%#= f.label :year %>
        <%= f.select :year_model_eq, options_for_select(Vehicle.order(:year_model).map {|p| [ p.year_model ]}.uniq, @q.year_model_eq), {prompt: "Select Year"} , {class: 'form-control'} %>
      </div>

      <div class="col-auto">
        <%#= f.label :brand %>
        <%= f.select :vehicle_brand_id_eq, options_for_select(VehicleBrand.order(:name).map {|p| [ p.name, p.id ]}.uniq, @q.vehicle_brand_id_eq), {prompt: "Select Brand"}, {class: 'form-control'} %>
      </div>

      <div class="col-auto">
        <%#= f.label :model %>
        <%= f.grouped_collection_select :vehicle_model_id_eq, VehicleBrand.order(:name), :vehicle_model, :name, :id, :name, { include_blank: true, prompt: "Select Model"}, class: 'form-control' %>
      </div>

      <div class="col-auto">
        <%= f.submit "Search", class: 'btn btn-primary mb-2' %>
        <%= link_to "Clear", request.path, class:"btn btn-primary mb-2" %>
        <%= link_to 'Add Vehicle', new_vehicle_path, class: 'btn btn-primary mb-2' %>
      </div>
    </div>

  <% end %>

</div>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<%= render 'ransack' %>

<table class="table">
  <thead>
    <tr>
      <th>Year model</th>
      <th>Vehicle brand</th>
      <th>Vehicle model</th>
      <th>Chassis number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.order( :vehicle_brand_id, :year_model).each do |vehicle| %>
      <tr>
        <td><%= vehicle.year_model %></td>
        <td><%= vehicle.vehicle_brand.name %></td>
        <td><%= vehicle.vehicle_model.name %></td>
        <td><%= vehicle.chassis_number %></td>
        <td><%= link_to 'View Parts', vehicle %></td>
        <!-- <td><%#= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%#= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @vehicles %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<table class="table pt-4">
  <tr>
    <th>Year Model</th>
    <th>Brand</th>
    <th>Model</th>
    <th>Chassis Number</th>
  </tr>
  <tr>
    <td><%= @vehicle.year_model %></td>
    <td><%= @vehicle.vehicle_brand.name %></td>
    <td><%= @vehicle.vehicle_model.name %></td>
    <td><%= @vehicle.chassis_number %></td>
  </tr>
</table>

<h3 class="pt-4">Available Parts:</h3>
<table class="table">
  <tr>
    <th>Part</th>
    <th>Price</th>
    <th>Supplier</th>
  </tr>
  <% @vehicle.vehicle_parts.each do |vparts| %>
    <tr>
      <td><%= vparts.part.name %></td>
      <td></td>
      <td></td>
        <% vparts.prices.each do |pr| %>
        <tr>
          <td></td>
          <td><%= format_currency(pr.price) %></td>
          <td><%= pr.supplier.name %></td>
        </tr>
        <% end %>
    </tr>
  <% end %>
</table>


<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>